### ISSUE TITLE
bg subtraction and the manually annotate mid-frame semantic segmentation masks

### ISSUE THREAD

**Issue by ly-zhu** [arunbalajeev/binaural-sound-perception#1]
Hello! First of all, thank you so much for sharing this. I'm really impressed with the great work!

Would it be possible to share the scripts or more instructions on the background subtraction, sound-making target object, and your manual annotation of the middle frame in each split video?  and the train/val/test split? Thus, we can compare with you work. Thanks!

**Comment by ly-zhu** [comment]
Could you also please provide the necessary dataset setting files under the dataset folder (imported in dataset/__init__.py)?

**Comment by arunbalajeev** [comment]
Thanks for going through our code. 
I have also updated the files in datasets folder.

**Comment by arunbalajeev** [comment]
I shall update the codes for " background subtraction, sound-making target object, and your manual annotation of the middle frame in each split video" soon. Please refer our paper where we have good description of the same.
