### ISSUE TITLE
Dataset size

### ISSUE THREAD

**Issue by drydenwiebe** [arunbalajeev/binaural-sound-perception#10]
Hello,

In the paper for this work, it states that there are 64,250 video clips. When I download the dataset from the link, and run extract_videosegments.py on the directory, I only end up with 31569 frames in all of the split_videoframes directory.

@arunbalajeev do you have any idea why this is? I looked at the extraction scripts and it seems reasonable.

Thanks!

**Comment by arunbalajeev** [comment]
@drydenwiebe , thanks for the question.

Yes, you are right. You get around 32K clips from the middle frames of videosegments taken from timestamps of 0-2sec, 2-4th sec, 4-6th sec, and so on. We extract the next 32K clips from overlapping segments from time stamps of 1-3 sec, 3-5th sec, 5-7th sec, and so on.

Hope this helps you!!
