### ISSUE TITLE
missing optimizer_two5_SharedEnc

### ISSUE THREAD

**Issue by SaschaHornauer** [arunbalajeev/binaural-sound-perception#5]
Thank you for your paper, I think this is a very impressive contribution. I would really like to reproduce the results but I am running into several issues and some I can't fix myself. I am going to create a few issues here, one for each point found, so you may be able to fix the code and supply the additional data necessary.

**train_noBG_Paralleltask_depth** loads **optimizer_two5_SharedEnc_depth** which is in the repository, however, **train_noBG_Paralleltask** wants to load **optimizer_two5_SharedEnc** which is not in the repository:

```
  File "scripts/train_noBG_Paralleltask.py", line 19, in <module>
    import optimizer_two5_SharedEnc as optimizer
ModuleNotFoundError: No module named 'optimizer_two5_SharedEnc'
```

Please excuse if the line numbers do not fit your version, I had to remove comments at the top of the file to get around the future import issue.

**Comment by arunbalajeev** [comment]
Thanks for noting the error. 
I have attached the file: optimizer_two5_SharedEnc.py to the repository.
